
String excusas_fun[70] = {
"El codigo se perdio en el espacio-tiempo.",
"Los servidores estan siendo atacados por alienigenas.",
"Un dragon secuestro a nuestro mejor programador.",
"Estamos esperando a que la tecnologia avance para poder continuar.",
"La oficina fue invadida por zombies y tuvimos que evacuar.",
"Nuestro equipo esta sufriendo de amnesia colectiva y olvido como trabajar en el proyecto.",
"El edificio donde trabajamos fue declarado zona de desastre natural.",
"El cliente cambio de opinion sobre lo que quiere... otra vez.",
"La computadora principal cayo en un pozo sin fondo.",
"El internet dejo de funcionar en todo el mundo.",
"Un grupo de duendes robo nuestros archivos importantes.",
"El perro del vecino ladra demasiado fuerte y no podemos concentrarnos.",
"El gato piso el teclado y borro todo nuestro trabajo.",
"Estamos esperando a que pase la temporada de huracanes para poder avanzar.",
"El equipo esta distraido porque hay un concurso de comer pasteles en la oficina de al lado.",
"La impresora se quedo sin tinta y no podemos imprimir los documentos necesarios.",
"El aire acondicionado esta roto y hace demasiado calor para pensar con claridad.",
"El cafe se acabo y nadie puede trabajar sin el.",
"Un agujero negro aparecio en medio de la oficina y estamos tratando de resolverlo.",
"El fantasma de proyectos pasados nos esta persiguiendo y no podemos avanzar hasta que lo resolvamos.",
"El proyecto fue abducido por extraterrestres.",
"El equipo esta sufriendo de narcolepsia colectiva.", 
"El cliente quiere que agreguemos unicornios al proyecto. ",
"El edificio donde trabajamos fue transportado a otro plano dimensional. ",
"La computadora principal fue poseida por un demonio. ",
"El internet fue hackeado por un grupo de adolescentes rebeldes. ",
"El equipo esta distraido porque hay un festival de globos afuera.", 
"El perro del vecino esta ladrando en Morse y no podemos descifrar el mensaje. ",
"El gato se comio todos los cables de las computadoras. ",
"El equipo esta sufriendo de una intoxicacion alimentaria por comer demasiados tacos.", 
"El aire acondicionado esta haciendo ruidos extraños y nos da miedo usarlo.", 
"El cafe fue reemplazado por te de hongos psicodelicos. ",
"El equipo esta distraido porque hay un concurso de lanzamiento de aviones de papel en la oficina de al lado.", 
"El fantasma de proyectos pasados regreso y ahora esta jugando bromas pesadas. ",
"El edificio donde trabajamos fue invadido por monstruos marinos. ",
"El equipo esta sufriendo de una crisis existencial y no sabe si seguir adelante con el proyecto.", 
"El cliente quiere que agreguemos sirenas al proyecto.", 
"El equipo esta distraido porque hay un concierto de heavy metal afuera. ",
"El aire acondicionado fue reemplazado por un ventilador gigante que hace mucho ruido. ",
"El equipo esta sufriendo de una maldicion gitana que les impide trabajar en el proyecto.", 
"El edificio donde trabajamos fue transportado al futuro. ",
"El equipo esta distraido porque hay un concurso de comer hot dogs en la oficina de al lado.", 
"El cliente quiere que agreguemos dragones al proyecto.",
"El equipo esta sufriendo de una sobredosis de azúcar por comer demasiados dulces.", 
"El aire acondicionado fue reemplazado por un ventilador que lanza confeti.", 
"El equipo esta distraido porque hay un festival de música electronica afuera.", 
"El edificio donde trabajamos fue transportado a una dimension paralela.", 
"El equipo esta sufriendo de una crisis de identidad y no sabe quienes son. ",
"El cliente quiere que agreguemos robots asesinos al proyecto. ",
"El equipo esta distraido porque hay un concurso de lanzamiento de martillos en la oficina de al lado.", 
"El aire acondicionado fue reemplazado por un ventilador que lanza burbujas de jabon.", 
"El equipo esta sufriendo de una adiccion a los videojuegos y no pueden parar de jugar.", 
"El edificio donde trabajamos fue transportado a una galaxia lejana.", 
"El equipo esta distraido porque hay un festival de comida callejera afuera.", 
"El cliente quiere que agreguemos zombis al proyecto. ",
"El equipo esta sufriendo de una crisis creativa y no saben que hacer. ",
"El aire acondicionado fue reemplazado por un ventilador que lanza flores.", 
"El equipo esta distraido porque hay un concurso de comer helado en la oficina de al lado.", 
"El edificio donde trabajamos fue transportado a una linea temporal alternativa.", 
"El equipo esta sufriendo de una sobredosis de cafeina por beber demasiado cafe. ",
"El cliente quiere que agreguemos vampiros al proyecto. ",
"El equipo esta distraido porque hay un festival de arte callejero afuera. ",
"El aire acondicionado fue reemplazado por un ventilador que lanza confeti brillante. ",
"El equipo esta sufriendo de una crisis emocional y no pueden trabajar. ",
"El edificio donde trabajamos fue transportado a una dimension desconocida.", 
"El equipo esta distraido porque hay un concurso de comer pizza en la oficina de al lado.", 
"El cliente quiere que agreguemos aliens al proyecto", 
"El cliente quiere que agreguemos piratas al proyecto",
"El equipo esta sufriendo de una crisis de confianza y no cree en sus habilidades",
"El cliente quiere que agreguemos dinosaurios al proyecto."};
