String excusas[96] = {
    "Cambios en los requisitos del cliente.",
    "Escasez de recursos humanos.",
    "Problemas con la calidad de los entregables.",
    "Retrasos en la entrega de proveedores.",
    "Problemas de integracion de sistemas.",
    "Falta de claridad en los objetivos del proyecto.",
    "Problemas de comunicacion dentro del equipo.",
    "Conflictos internos en el equipo.",
    "Cambios en la direccion estrategica de la empresa.",
    "Problemas de financiamiento o presupuesto insuficiente.",
    "Problemas de priorizacion de tareas.",
    "Cambios en la tecnologia o plataforma utilizada.",
    "Requisitos legales o regulatorios cambiantes.",
    "Cambios en el mercado o competencia.",
    "Problemas de seguridad de datos.",
    "Problemas de rendimiento en el hardware.",
    "Problemas de rendimiento en el software.",
    "Ausencia prolongada de un miembro clave del equipo.",
    "Enfermedad prolongada de un miembro clave del equipo.",
    "Problemas de disponibilidad de equipo.",
    "Problemas de disponibilidad de hardware.",
    "Falta de entrenamiento o habilidades insuficientes en el equipo.",
    "Problemas imprevistos de salud o desastres naturales que afectan la ubicacion del equipo.",
    "Cambios frecuentes en los requisitos del cliente debido a la naturaleza ágil de la metodologia Scrum.",
    "Falta de compromiso por parte de los stakeholders clave en la toma de decisiones.",
    "Problemas de estimacion de tiempo y esfuerzo en el proceso de sprint planning.",
    "Bloqueos en el flujo de trabajo debido a la dependencia de entregables de otros equipos.",
    "Dificultades en la priorizacion de las historias de usuario en el backlog.",
    "Problemas de escalabilidad al expandir el proyecto a nivel empresarial.",
    "Reasignacion de recursos a otros proyectos criticos de la organizacion.",
    "Cambios en la hoja de ruta del proyecto debido a la evolucion del mercado.",
    "Limitaciones de capacidad en el equipo Scrum para abordar múltiples proyectos simultáneamente.",
    "Dificultades en la identificacion y gestion de riesgos de forma proactiva.",
    "Cambios en las regulaciones gubernamentales que afectan la planificacion del proyecto.",
    "Falta de claridad en los roles y responsabilidades dentro del equipo Scrum.",
    "Problemas de comunicacion interdepartamental entre los equipos de desarrollo y QA.",
    "Falta de acceso o disponibilidad de herramientas y recursos tecnologicos clave.",
    "Retrasos en la aprobacion de presupuesto por parte del comite de financiamiento.",
    "Cambios en la dinámica de la fuerza laboral, como rotacion de personal clave.",
    "Problemas con la retencion del conocimiento debido a la salida de miembros del equipo.",
    "Falta de capacitacion y certificacion Scrum en el equipo de desarrollo.",
    "Cambios en la estrategia de externalizacion que afectan la subcontratacion de tareas especificas.",
    "Requerimientos tecnicos cambiantes debido a avances en la tecnologia.",
    "Incertidumbre en la disponibilidad de recursos de hardware y software.",
    "Problemas en la gestion de cambios en el alcance del proyecto.",
    "Cambios en la estructura organizativa de la empresa.",
    "Dificultades en la gestion de la calidad y control de procesos.",
    "Errores en la estimacion de costos y duracion del proyecto.",
    "Rechazo de propuestas por parte de inversores o patrocinadores del proyecto.",
    "Desafios en la gestion de la resistencia al cambio dentro de la organizacion.",
    "Problemas de gestion del tiempo debido a la sobrecarga de trabajo del equipo.",
    "Dificultades en la gestion de riesgos y contingencias.",
    "Cambios en la normativa de cumplimiento que afectan el proyecto.",
    "Falta de alineacion entre los objetivos del proyecto y la estrategia de la empresa.",
    "Problemas en la disponibilidad de datos y recursos clave.",
    "Errores en la documentacion y seguimiento de los entregables del proyecto.",
    "Dificultades en la gestion de la moral y motivacion del equipo.",
    "Cambios en la dinámica de mercado que requieren adaptaciones constantes.",
    "Problemas de coordinacion entre equipos multidisciplinarios.",
    "Cambios en la tecnologia de infraestructura que impactan en el desarrollo.",
    "Errores en la gestion de proveedores y contratistas externos.",
    "Dificultades en la identificacion de KPIs efectivos para el proyecto.",
    "Cambios en las prioridades estrategicas de la alta direccion.",
    "Problemas en la gestion del conocimiento y la documentacion del proyecto.",
    "Cambios en las tendencias de la industria que requieren ajustes constantes.",
    "Errores en la asignacion de recursos humanos a tareas especificas.",
    "Dificultades en la alineacion de expectativas con los stakeholders.",
    "Cambios en el equipo de gestion del proyecto.",
    "Problemas con la comunicacion con partes interesadas externas.",
    "Cambios en la demanda del mercado que requieren ajustes en la estrategia.",
    "Dificultades en la gestion de la carga de trabajo del equipo.",
    "Cambios en las preferencias de los clientes que impactan en los entregables.",
    "Errores en la gestion de la documentacion y control de versiones.",
    "Problemas con la disponibilidad de instalaciones o espacio de trabajo.",
    "Cambios en la politica de recursos humanos que afectan la contratacion.",
    "Dificultades en la gestion de la colaboracion interdepartamental.",
    "Cambios en la estrategia de marketing que requieren modificaciones en el proyecto.",
    "Problemas con la gestion de la cadena de suministro y adquisiciones.",
    "Errores en la planificacion de la capacitacion y desarrollo del equipo.",
    "Dificultades en la gestion de expectativas de los patrocinadores del proyecto.",
    "Cambios en las preferencias del usuario final que requieren ajustes en el diseño.",
    "Problemas con la gestion de la diversidad y la inclusion en el equipo.",
    "Cambios en las politicas de seguridad de la informacion que afectan el proyecto.",
    "Dificultades en la gestion de los procesos de aprobacion internos.",
    "Errores en la gestion de la gestion del rendimiento y evaluacion del equipo.",
    "Cambios en la estrategia de comercializacion que requieren adaptaciones constantes.",
    "Lamentablemente, no podemos avanzar en el proyecto debido a un cambio de prioridades por parte de un stakeholder clave.",
    "Estamos experimentando retrasos en la entrega de requisitos claros por parte de los stakeholders.",
    "La falta de compromiso de los stakeholders está impactando negativamente en el progreso del proyecto.",
    "Hemos enfrentado desafios en la gestion de expectativas de los stakeholders.",
    "La complejidad de las demandas de múltiples stakeholders ha ralentizado nuestro avance.",
    "Cambios frecuentes en las expectativas de los stakeholders han impactado en la planificacion.",
    "Problemas en la comunicacion con stakeholders externos han generado confusiones.",
    "Requerimos la aprobacion de un stakeholder antes de avanzar en esta fase del proyecto.",
    "Estamos trabajando en abordar las preocupaciones de un stakeholder critico para el proyecto.",
    "La falta de alineacion entre los stakeholders ha generado conflictos y obstáculos en el progreso."
    };
