String excusas_firmware_hardware[78] = {
    "Cambios frecuentes en los requisitos de firmware por parte del cliente.",
    "Escasez de ingenieros con experiencia en desarrollo de hardware.",
    "Problemas en el diseño de hardware que afectan el desarrollo de firmware.",
    "Retrasos en la recepcion de componentes criticos por parte de proveedores.",
    "Problemas de integracion de firmware con hardware.",
    "Cambios en la arquitectura de hardware que requieren ajustes en el firmware.",
    "Dificultades en la identificacion de requisitos de firmware claros.",
    "Conflictos internos en el equipo de desarrollo de hardware y firmware.",
    "Cambios en la estrategia de diseño de hardware de la empresa.",
    "Problemas de financiamiento o presupuesto insuficiente para el desarrollo de hardware y firmware.",
    "Problemas de priorizacion de tareas de desarrollo de firmware y hardware.",
    "Cambios en la tecnologia utilizada en el hardware que impactan en el firmware.",
    "Requisitos de certificacion cambiantes que afectan el desarrollo de firmware y hardware.",
    "Cambios en el mercado de componentes de hardware que afectan la planificacion.",
    "Problemas de seguridad de firmware y hardware que requieren correcciones.",
    "Problemas de rendimiento en el firmware que afectan la funcionalidad del hardware.",
    "Enfermedad o ausencia prolongada de un ingeniero clave en el equipo de desarrollo.",
    "Problemas de disponibilidad de herramientas y equipos de prueba especificos.",
    "Falta de capacitacion o habilidades insuficientes en el equipo de desarrollo de firmware y hardware.",
    "Problemas imprevistos de salud o desastres naturales que afectan la ubicacion del equipo.",
    "Cambios en los estandares de comunicacion entre hardware y firmware.",
    "Falta de recursos para pruebas exhaustivas de hardware y firmware.",
    "Problemas en la gestion de cambios en la arquitectura de firmware y hardware.",
    "Cambios en las regulaciones de cumplimiento que afectan el firmware y hardware.",
    "Falta de claridad en los roles y responsabilidades dentro del equipo de desarrollo.",
    "Problemas en la comunicacion entre ingenieros de firmware y hardware.",
    "Cambios en la disponibilidad de componentes especificos.",
    "Dificultades en la identificacion y gestion de riesgos especificos de firmware y hardware.",
    "Retrasos en la aprobacion de presupuesto para pruebas y validacion de hardware y firmware.",
    "Cambios en la estrategia de externalizacion que afectan el desarrollo de firmware y hardware.",
    "Problemas de compatibilidad entre firmware y diferentes versiones de hardware.",
    "Errores en la estimacion de tiempos y costos de desarrollo de firmware y hardware.",
    "Dificultades en la gestion del conocimiento en el desarrollo de firmware y hardware.",
    "Cambios en las tendencias de la industria que requieren adaptaciones constantes.",
    "Problemas con la disponibilidad de herramientas de depuracion y programacion.",
    "Errores en la planificacion de pruebas de hardware y firmware.",
    "Dificultades en la alineacion de expectativas con los clientes y usuarios finales.",
    "Cambios en la estrategia de adquisiciones que afectan la seleccion de componentes de hardware.",
    "Cambios en las preferencias del usuario final que requieren ajustes en el firmware.",
    "Errores en la gestion de proyectos y plazos de entrega.",
    "Cambios en las normas de seguridad y cumplimiento de la industria.",
    "Problemas de interoperabilidad con otros sistemas y dispositivos.",
    "Cambios en la disponibilidad de componentes obsoletos.",
    "Errores en la gestion de recursos y personal.",
    "Cambios en las regulaciones de exportacion que afectan el proyecto.",
    "Problemas con la resolucion de problemas tecnicos inesperados.",
    "Cambios en la estrategia de marketing que requieren modificaciones en el hardware y firmware.",
    "Errores en la gestion de cambios en la arquitectura de firmware y hardware.",
    "Cambios en las preferencias de diseño por parte de la alta direccion.",
    "Problemas en la validacion y prueba de componentes de hardware.",
    "Cambios en las politicas de gestion de configuracion que impactan en el desarrollo.",
    "Errores en la planificacion de recursos de hardware y firmware.",
    "Dificultades en la gestion de la cadena de suministro y adquisiciones de componentes.",
    "Cambios en las preferencias de diseño de firmware por parte de los clientes.",
    "Problemas con la comunicacion y coordinacion entre equipos de firmware y hardware.",
    "Cambios en la estrategia de fabricacion que afectan la produccion de hardware.",
    "Errores en la estimacion de costos de desarrollo de firmware y hardware.",
    "Dificultades en la resolucion de problemas tecnicos durante la fase de diseño.",
    "Cambios en la disponibilidad de tecnologia de fabricacion.",
    "Problemas con la estabilidad y confiabilidad del hardware.",
    "Cambios en los requisitos de prueba de firmware y hardware.",
    "Errores en la documentacion de diseño y especificaciones tecnicas.",
    "Problemas de coordinacion en la validacion de hardware y firmware.",
    "Cambios en las normativas de seguridad electrica y EMC que afectan la certificacion.",
    "Dificultades en la validacion de sistemas en condiciones ambientales adversas.",
    "Cambios en la estrategia de suministro de componentes que afectan la produccion.",
    "Errores en la estimacion de consumo de energia en firmware y hardware.",
    "Problemas con la deteccion y correccion de errores en el firmware.",
    "Cambios en la estrategia de gestion de la calidad que requieren ajustes en el proceso.",
    "Problemas con la adquisicion de herramientas de depuracion y pruebas de hardware.",
    "Cambios en la estrategia de pruebas y validacion que afectan los plazos de entrega.",
    "Errores en la coordinacion entre ingenieros de software y hardware en el desarrollo del firmware.",
    "Cambios en la disponibilidad de sistemas de emulacion y simulacion.",
    "Problemas con la gestion de proveedores y contratistas externos de hardware.",
    "Cambios en los estandares de comunicacion entre diferentes dispositivos de hardware.",
    "Errores en la identificacion y correccion de vulnerabilidades de seguridad en el firmware.",
    "Problemas en la disponibilidad de hardware de prototipado y desarrollo.",
    "Cambios en los objetivos de eficiencia energetica que requieren ajustes en el diseño"};
